; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs | FileCheck %s
target triple = "aarch64-unknown-linux-gnu"

define dso_local void @fpr_to_gpr(<16 x i8> noundef %q0) #0 {
; CHECK-LABEL: fpr_to_gpr:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp q0, q0, [sp, #-32]!
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    ldp x0, x1, [sp], #32
; CHECK-NEXT:    //APP
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
entry:
	%q0.addr = alloca <16 x i8>, align 16
	%x0 = alloca <16 x i8>, align 16
	store <16 x i8> %q0, ptr %q0.addr, align 16
	%0 = load <16 x i8>, ptr %q0.addr, align 16
	store <16 x i8> %0, ptr %x0, align 16
	%1 = load <16 x i8>, ptr %x0, align 16
	call void asm sideeffect "", "{x0}"(<16 x i8> %1)
	ret void
}
